build:
  image: docker:stable
  stage: build
  services:
    - docker:18.09.7-dind
  variables:
    DOCKER_HOST: tcp://localhost:2375
  script:
    - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY
    - docker build -t $CI_REGISTRY/web:latest -f infra/Dockerfile-Web .
    - docker push $CI_REGISTRY/web:latest