build:
  image: docker:20.10.16
  stage: build
  services:
    - docker:20.10.16-dind
  script:
    - sudo docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY
    - sudo docker build -t $CI_REGISTRY/web:latest -f infra/Dockerfile-Web .
    - sudo docker push $CI_REGISTRY/web:latest