# Utilise l'image officielle de PHP 8.2 avec Apache
FROM php:8.2-apache

# Installe le driver MongoDB
RUN pecl install mongodb && docker-php-ext-enable mongodb

# Copie les fichiers sources dans le dossier /var/www/html
COPY . /var/www/html
COPY php.ini /usr/local/etc/php/php.ini

# Se place dans le dossier /var/www/html
#WORKDIR /var/www/html

EXPOSE 80
CMD ["apache2-foreground"]
#CMD [ "php", "-S", "localhost:80"]
# ENTRYPOINT ["tail"]
# CMD ["-f","/dev/null"]