{
 "title": "New dashboard",
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   { "name": "composant", "query": "select id from composant;" }
  ]
 },
 "panels": [
  { "title": "Physique", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Utilisation du processeur (%)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 1 },
   "targets": [
    {
     "dataset": "monitoring",
     "rawSql": "SELECT date, valeur FROM monitoring.log WHERE metrique_id = 2 AND composant_id = $composant \nLIMIT 50 "
    }
   ]
  },
  {
   "title": "Usage du disque (Mb/s)",
   "type": "bargauge",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "dataset": "monitoring",
     "rawSql": "SELECT date, valeur FROM monitoring.log WHERE metrique_id = 4 AND composant_id = $composant \nLIMIT 50 "
    }
   ]
  },
  {
   "title": "Température (°C)",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 9 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "dataset": "monitoring",
     "rawSql": "SELECT date, valeur FROM monitoring.log WHERE metrique_id = 5 AND composant_id = $composant \nLIMIT 50 "
    }
   ]
  },
  {
   "title": "Utilisation de la mémoire (%)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 9 },
   "targets": [
    {
     "dataset": "monitoring",
     "rawSql": "SELECT date, valeur FROM monitoring.log WHERE metrique_id = 3 AND composant_id = $composant \nLIMIT 50 "
    }
   ]
  },
  { "title": "Réseau", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 17 } },
  {
   "title": "Temps de réponse (en ms)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 18 },
   "targets": [
    {
     "dataset": "monitoring",
     "rawSql": "SELECT date, valeur FROM monitoring.log WHERE metrique_id = 1 AND composant_id = $composant \nLIMIT 50 "
    }
   ]
  },
  {
   "title": "Traffic (Mb/s)",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 18 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "dataset": "monitoring",
     "rawSql": "SELECT date, valeur FROM monitoring.log WHERE metrique_id = 6 AND composant_id = $composant \nLIMIT 50 "
    }
   ]
  },
  {
   "title": "Débit (Mb/s)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 26 },
   "targets": [
    {
     "dataset": "monitoring",
     "rawSql": "SELECT date, valeur FROM monitoring.log WHERE metrique_id = 7 AND composant_id = $composant \nLIMIT 50 "
    }
   ]
  }
 ]
}