#cloud-config
users:
  - name: nderousseaux
    passwd: $1$Zk0NDqEp$DRjhMrBOD5CoFrfyp.dkr/
    groups: users,wheel
    sudo: ALL=(ALL) NOPASSWD:ALL
    lock_passwd: false
bootcmd:
  - loadkeys fr

repo_update: true
repo_upgrade: all

package_upgrade: true
packages:
  - wget

runcmd:
  # Debug SSH
  - sed -i 's/PasswordAuthentication no/PasswordAuthentication yes/g' /etc/ssh/sshd_config
  - systemctl restart sshd


  # On installe prometheus
  - wget https://github.com/prometheus/prometheus/releases/download/v2.48.0/prometheus-2.48.0.linux-amd64.tar.gz
  - tar xvfz prometheus-2.48.0.linux-amd64.tar.gz
  - mv prometheus-2.48.0.linux-amd64/prometheus /
  - rm -rf prometheus-2.48.0.linux-amd64*
  - chmod +x prometheus

  # On crée le fichier de config
  - echo "global:" > /prometheus.yml
  - echo "  scrape_interval: 15s" >> /prometheus.yml
  - echo "  evaluation_interval: 15s" >> /prometheus.yml
  - echo "scrape_configs:" >> /prometheus.yml
  - echo "  - job_name: 'prometheus'" >> /prometheus.yml
  - echo "    static_configs:" >> /prometheus.yml
  - echo "    - targets: ['localhost:9090']" >> /prometheus.yml
  - echo "  - job_name: 'VM1'" >> /prometheus.yml
  - echo "    static_configs:" >> /prometheus.yml
  - echo "    - targets: ['192.168.0.194:9100']" >> /prometheus.yml

  # On configure prometheus comme un service
  - echo "[Unit]" > /etc/systemd/system/prometheus.service
  - echo "Description=Prometheus Agent" >> /etc/systemd/system/prometheus.service
  - echo "" >> /etc/systemd/system/prometheus.service
  - echo "[Service]" >> /etc/systemd/system/prometheus.service
  - echo "User=root" >> /etc/systemd/system/prometheus.service
  - echo "ExecStart=/bin/sh -c '/prometheus --config.file=prometheus.yml'" >> /etc/systemd/system/prometheus.service
  - echo "Restart=always" >> /etc/systemd/system/prometheus.service
  - echo "" >> /etc/systemd/system/prometheus.service
  - echo "[Install]" >> /etc/systemd/system/prometheus.service
  - echo "WantedBy=multi-user.target" >> /etc/systemd/system/prometheus.service

  # On démarre node_exporter
  - systemctl daemon-reload
  - systemctl start prometheus.service