FROM alpine:latest

# Installer les paquets nécessaires à la compilation
RUN apk update && apk add --no-cache \
	build-base \
	cmake \
	libssh2-dev \
	sqlite-dev

# Copier les fichiers sources, les headers et le CMakeLists.txt
COPY src /app/src
COPY inc /app/inc
COPY CMakeLists.txt /app/CMakeLists.txt
COPY build.sh /app/build.sh

# Se place dans le dossier /app
WORKDIR /app

# Lance le script de compilation, avec comme argument le type de programme à
# compiler
ARG PROG_TYPE
RUN chmod +x build.sh
RUN sh build.sh "$PROG_TYPE"