#cloud-config
users:
  - name: nderousseaux
    passwd: $1$Zk0NDqEp$DRjhMrBOD5CoFrfyp.dkr/
    groups: users,wheel
    sudo: ALL=(ALL) NOPASSWD:ALL
    lock_passwd: false
bootcmd:
  - loadkeys fr

repo_update: true
repo_upgrade: all

package_upgrade: true
packages:
  - wget

runcmd:

  # Debug SSH
  - sed -i 's/PasswordAuthentication no/PasswordAuthentication yes/g' /etc/ssh/sshd_config
  - systemctl restart sshd


  # On installe node_exporter
  - cd /root
  - wget https://github.com/prometheus/node_exporter/releases/download/v1.2.2/node_exporter-1.2.2.linux-amd64.tar.gz
  - tar xvfz node_exporter-1.2.2.linux-amd64.tar.gz
  - mv node_exporter-1.2.2.linux-amd64/node_exporter .
  - rm -rf node_exporter-1.2.2.linux-amd64*
  - chmod +x node_exporter

  # On configure node_exporter comme un service
  - echo "[Unit]" > /etc/systemd/system/node_exporter.service
  - echo "Description=Node Exporter Agent" >> /etc/systemd/system/node_exporter.service
  - echo "" >> /etc/systemd/system/node_exporter.service
  - echo "[Service]" >> /etc/systemd/system/node_exporter.service
  - echo "User=root" >> /etc/systemd/system/node_exporter.service
  - echo "ExecStart=/bin/sh -c '/node_exporter'" >> /etc/systemd/system/node_exporter.service
  - echo "Restart=always" >> /etc/systemd/system/node_exporter.service
  - echo "" >> /etc/systemd/system/node_exporter.service
  - echo "[Install]" >> /etc/systemd/system/node_exporter.service
  - echo "WantedBy=multi-user.target" >> /etc/systemd/system/node_exporter.service

  # On démarre node_exporter
  - systemctl daemon-reload
  - systemctl start node_exporter.service