# Dockerfile pour une instance web
FROM debian:latest

# Mise à jour du système
RUN apt-get update && apt-get upgrade -y

# Installation des paquets nécessaires
RUN apt install -y git apache2 php

# Suppression du contenu du dossier web
RUN rm -rf /var/www/html/*

# Configuration du serveur apache
RUN echo "ServerName localhost" >> /etc/apache2/apache2.conf
RUN a2enmod ssl
RUN a2ensite default-ssl

# Clonage du dépôt ou se trouve le site web
RUN git clone https://user:glpat-sEbppxiL7vYxdhy7-QXg@git.unistra.fr/fseel/projet-master-23-24.git

# Permission de pull par n'importe qui
RUN git config --system --add safe.directory '*'

# Copie du site web dans le dossier web
RUN mkdir /var/www/html/com
RUN cp -r projet-master-23-24/site-comm/* /var/www/html/com

# Certificat SSL
RUN openssl req -x509 -nodes -days 365 -newkey rsa:2048 -sha256 \
	-subj "/C=FR/ST=Bas-Rhin/L=Strasbourg/O=Unistra/CN=LEFEVRE Matthieu" \
	-out /etc/apache2/server.crt -keyout /etc/apache2/server.key 
RUN chmod 440 /etc/apache2/server.crt /etc/apache2/server.key
RUN sed -i 's/\/etc\/ssl\/certs\/ssl-cert-snakeoil.pem/\/etc\/apache2\/server.crt/' /etc/apache2/sites-available/default-ssl.conf
RUN sed -i 's/\/etc\/ssl\/private\/ssl-cert-snakeoil.key/\/etc\/apache2\/server.key/' /etc/apache2/sites-available/default-ssl.conf

# Exposition du port 80 et 443
EXPOSE 443

# Lancement du serveur apache
CMD ["apachectl", "-D", "FOREGROUND"]

