network:
  version: 2
  ethernets:
    ens4:
      dhcp4: false
      mtu: 1400
    ens5:
      dhcp4: false
      mtu: 1400
    ens6:
      dhcp4: false
      mtu: 1600
    ens7:
      dhcp4: false
      mtu: 1400
    ens8:
      dhcp4: false
      mtu: 1400
    ens9:
      dhcp4: false
      mtu: 1400
    ens10:
      dhcp4: false
      mtu: 1400
    ens11:
      dhcp4: false
      mtu: 1400
    ens12:
      dhcp4: false
      mtu: 1400
    ens13:
      dhcp4: false
      mtu: 1400
    ens14:
      dhcp4: false
      mtu: 1400
    ens15:
      dhcp4: false
      mtu: 1400
    ens16:
      dhcp4: false
      mtu: 1400
    ens17:
      dhcp4: false
      mtu: 1400
  tunnels:
    vxlan2:
      mode: vxlan
      local: 10.0.1.2
      mac-learning: false
      id: 2
      port: 9001
    vxlan3:
      mode: vxlan
      local: 10.0.1.2
      mac-learning: false
      id: 3
      port: 9001
    vxlan4:
      mode: vxlan
      local: 10.0.1.2
      mac-learning: false
      id: 4
      port: 9001
    vxlan5:
      mode: vxlan
      local: 10.0.1.2
      mac-learning: false
      id: 5
      port: 9001
    vxlan6:
      mode: vxlan
      local: 10.0.1.2
      mac-learning: false
      id: 6
      port: 9001
    vxlan7:
      mode: vxlan
      local: 10.0.1.2
      mac-learning: false
      id: 7
      port: 9001
    vxlan8:
      mode: vxlan
      local: 10.0.1.2
      mac-learning: false
      id: 8
      port: 9001
    vxlan9:
      mode: vxlan
      local: 10.0.1.2
      mac-learning: false
      id: 9
      port: 9001
    vxlan10:
      mode: vxlan
      local: 10.0.1.2
      mac-learning: false
      id: 10
      port: 9001
    vxlan11:
      mode: vxlan
      local: 10.0.1.2
      mac-learning: false
      id: 11
      port: 9001
    vxlan12:
      mode: vxlan
      local: 10.0.1.2
      mac-learning: false
      id: 12
      port: 9001
    vxlan12:
      mode: vxlan
      local: 10.0.1.2
      mac-learning: false
      id: 12
      port: 9001
    vxlan13:
      mode: vxlan
      local: 10.0.1.2
      mac-learning: false
      id: 13
      port: 9001
    vxlan14:
      mode: vxlan
      local: 10.0.1.2
      mac-learning: false
      id: 14
      port: 9001
    vxlan15:
      mode: vxlan
      local: 10.0.1.2
      mac-learning: false
      id: 15
      port: 9001
  bridges:
    vmbr2:
      interfaces: [vxlan2]
      mtu: 1400
      parameters:
        stp: false
        #priority: 100
    vmbr3:
      interfaces: [vxlan3]
      mtu: 1400
      routes:
        - to: 10.2.0.0/16
          via: 10.2.255.254
          metric: 100
      nameservers:
        search: [pm2023]
        addresses: [10.2.255.254]
      parameters:
          stp: false
    vmbr4:
      interfaces: [vxlan4]
      mtu: 1400
      parameters:
        stp: false
    vmbr5:
      interfaces: [vxlan5]
      mtu: 1400
      parameters:
        stp: false
    vmbr6:
      interfaces: [vxlan6]
      mtu: 1400
      parameters:
        stp: false
    vmbr7:
      interfaces: [vxlan7]
      mtu: 1400
      parameters:
        stp: false
    vmbr8:
      interfaces: [vxlan8]
      mtu: 1400
      parameters:
        stp: false
    vmbr9:
      interfaces: [vxlan9]
      mtu: 1400
      parameters:
        stp: false
    vmbr10:
      interfaces: [vxlan10]
      mtu: 1400
      parameters:
        stp: false
    vmbr11:
      interfaces: [vxlan11]
      mtu: 1400
      parameters:
        stp: false
    vmbr12:
      interfaces: [vxlan12]
      mtu: 1400
      parameters:
        stp: false
    vmbr12:
      interfaces: [vxlan12]
      mtu: 1400
      parameters:
        stp: false
    vmbr13:
      interfaces: [vxlan13]
      mtu: 1400
      parameters:
        stp: false
    vmbr14:
      interfaces: [vxlan14]
      mtu: 1400
      parameters:
        stp: false
    vmbr15:
      interfaces: [vxlan15]
      mtu: 1400
      parameters:
        stp: false
